---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Download Tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz
    dest: /tmp/tomcat.tar.gz

- name: Extract Tomcat
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: /opt/
    remote_src: yes

- name: Make Tomcat scripts executable
  file:
    path: "/opt/apache-tomcat-9.0.88/bin/{{ item }}"
    mode: '0755'
  loop:
    - startup.sh
    - catalina.sh

- name: Start Tomcat
  shell: /opt/apache-tomcat-9.0.88/bin/startup.sh
